"""
超轻量级控制界面 - ESP32-C3内存优化版
解决内存分配失败问题，添加实时日志
"""

def get_lite_html():
    """极简HTML - 保留所有功能，最大压缩"""
    return """<!DOCTYPE html><html><head><meta charset="UTF-8"><title>思思桌面</title><style>body{font-family:sans-serif;margin:5px;background:#f5f5f5}h1{text-align:center;margin:10px 0;color:#333}.card{background:white;padding:8px;margin:5px 0;border-radius:3px;box-shadow:0 1px 3px rgba(0,0,0,0.1)}.btn{background:#4CAF50;color:white;padding:6px 10px;margin:2px;text-decoration:none;border-radius:3px;display:inline-block;font-size:12px}.btn-red{background:#F44336}.btn-blue{background:#2196F3}#log{background:#000;color:#0f0;padding:5px;height:120px;overflow-y:scroll;font-family:monospace;font-size:11px;border-radius:3px}.status{background:#eee;padding:3px;margin:3px 0;font-size:11px}</style></head><body><h1>思思桌面控制</h1><div class="card"><b>音频LED控制</b><br><a href="/api/led/off" class="btn btn-red">关闭</a><a href="/api/led/audio" class="btn btn-blue">音频特效</a><a href="/api/led/test" class="btn">测试</a></div><div class="card"><b>减速电机</b><br><a href="/api/motor/forward" class="btn">正转10秒</a><a href="/api/motor/backward" class="btn btn-red">反转10秒</a><a href="/api/motor/stop" class="btn">停止</a></div><div class="card"><b>电磁铁</b><br><a href="/api/electromagnet/on" class="btn">开启</a><a href="/api/electromagnet/off" class="btn btn-red">关闭</a></div><div class="card"><b>步进电机</b><br><a href="/api/stepper/90" class="btn">90度</a><a href="/api/stepper/180" class="btn">180度</a><a href="/api/stepper/360" class="btn">360度</a><a href="/api/stepper/swing" class="btn btn-blue">摆动</a><a href="/api/stepper/stop" class="btn btn-red">停止</a></div>
<div class="card"><b>距离传感器</b><br><a href="/api/sensor/distance" class="btn btn-blue">读取距离</a><a href="/api/sensor/test" class="btn">传感器测试</a></div><div class="card"><b>系统状态</b><br><a href="/api/status" class="btn btn-blue">状态</a><a href="/api/test" class="btn">测试</a><div id="status" class="status">点击状态按钮查看</div></div><div class="card"><b>实时日志</b><div id="log"></div><button onclick="clearLog()" style="padding:3px 8px;margin-top:3px;font-size:11px">清空</button></div>

<script>var c=0;function addLog(m){var l=document.getElementById('log'),t=new Date().toLocaleTimeString();c++;l.innerHTML+='['+c+'] '+t+' - '+m+'<br>';l.scrollTop=l.scrollHeight;if(c>50){var lines=l.innerHTML.split('<br>');l.innerHTML=lines.slice(-30).join('<br>');c=30}}function clearLog(){document.getElementById('log').innerHTML='';c=0;addLog('日志已清空')}window.onload=function(){addLog('思思桌面控制台启动');addLog('ESP32-C3设备已连接')};document.addEventListener('click',function(e){if(e.target.tagName==='A'&&e.target.href.indexOf('/api/')>-1){e.preventDefault();var url=e.target.href,action=e.target.textContent;addLog('执行: '+action);var xhr=new XMLHttpRequest();xhr.open('GET',url);xhr.timeout=5000;xhr.onload=function(){if(xhr.status===200){try{var data=JSON.parse(xhr.responseText);if(data.status==='success'){addLog('✅ '+action+' 成功');if(data.message)addLog('响应: '+data.message);if(url.indexOf('/api/status')>-1&&data.data){var statusDiv=document.getElementById('status'),info='';if(data.data.wifi)info+='WiFi: '+data.data.wifi.ip+' ';if(data.data.memory)info+='内存: '+data.data.memory+'KB ';if(data.data.uptime)info+='运行: '+data.data.uptime+'s';statusDiv.innerHTML=info}}else{addLog('❌ '+action+' 失败');if(data.error)addLog('错误: '+data.error)}}catch(err){addLog('✅ '+action+' 完成')}}else{addLog('❌ HTTP错误: '+xhr.status)}};xhr.onerror=function(){addLog('❌ 网络错误')};xhr.ontimeout=function(){addLog('❌ 请求超时')};xhr.send()}});</script>
</body></html>"""